name: "Hello World"
description: "Greet someone and record the time"
inputs:
  reg-address: # id of input
    description: "an address for a request"
    required: true
    default: ""
runs:
  using: "node16"
  main: "index.js"
